name: ci-test-masahiro # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary:  demo snap for gitlab cicd
description: |
  Test snap conatins very naive calculation and two test programs.
  test1 will pass, test2 will fail.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  test1:
    command: test1.exe
  test2:
    command: test2.exe
  App:
    command: App.exe

parts:
  test1:
    # See 'snapcraft plugins'
    plugin: make
    source: src
    override-build: |
      cd MinusTest
      make
      cp test1.exe $SNAPCRAFT_PART_INSTALL
  test2:
    plugin: make
    source: src
    override-build: |
      cd CalcTest
      make
      cp test2.exe $SNAPCRAFT_PART_INSTALL
  app:
    plugin: make
    source: src
    override-build: |
      cd App
      make
      cp App.exe $SNAPCRAFT_PART_INSTALL

